yarnPath: .yarn/releases/yarn-3.6.3.cjs
logFilters:
    - code: YN0013 
      level: discard
npmScopes:
  "here":
    npmRegistryServer: "https://repo.platform.here.com/artifactory/api/npm/maps-api-for-javascript/"
