# syntax=docker/dockerfile:1

FROM --platform=$BUILDPLATFORM node:25 AS build

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml .
COPY .yarn .yarn
COPY packages packages
COPY .git .git

RUN yarn --network-timeout 1000000 && yarn build

FROM nginxinc/nginx-unprivileged:mainline-alpine

COPY docker/nginx.conf.custom /etc/nginx/conf.d/default.conf
COPY --from=build /app/packages/app/build /usr/share/nginx/html

EXPOSE 8080
