FROM --platform=$BUILDPLATFORM node:current AS build

WORKDIR /src

RUN apt update \
    && apt install -y --no-install-recommends git \
    && git clone --single-branch -b main https://git.v0l.io/Kieran/snort \
    && cd snort \
    && yarn --network-timeout 1000000 \
    && yarn build

FROM nginxinc/nginx-unprivileged:mainline-alpine

COPY docker/nginx.conf.custom /etc/nginx/conf.d/default.conf
COPY --from=build /src/packages/app/build /usr/share/nginx/html

EXPOSE 8080
