FROM nginxinc/nginx-unprivileged:mainline-alpine

ARG VERSION_ARG=0
ENV VERSION=$VERSION_ARG

LABEL org.opencontainers.image.title="Snort"
LABEL org.opencontainers.image.description="Nostr web UI (snort.social)"

COPY packages/app/build /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
