FROM --platform=$BUILDPLATFORM node:current AS build

RUN yarn --network-timeout 1000000 && \
         yarn build

FROM nginxinc/nginx-unprivileged:mainline-alpine

COPY docker/nginx.conf.custom /etc/nginx/conf.d/default.conf
COPY --from=build packages/app/build /usr/share/nginx/html

EXPOSE 8080
